name: cotree_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  serverpod_auth_client: 2.9.1
  serverpod_flutter: 2.9.1
  cotree_client:
    path: ../cotree_client


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.4
  provider: ^6.1.2
  serverpod_auth_email_flutter: 2.9.1
  serverpod_auth_shared_flutter: 2.9.1
  serverpod_auth_google_flutter: 2.9.1
  serverpod_auth_apple_flutter: 2.9.1
  file_picker: ^8.0.0
  flutter_steps: ^1.0.5
  flutter_otp_text_field: ^1.5.1+1
  path: ^1.8.3
  choice: ^2.3.2
  face_pile: ^0.0.2
  heroicons: ^0.11.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.7
  intl: ^0.20.2
  duration_picker: ^1.2.0
  board_datetime_picker: ^2.8.0
  numberpicker: ^2.1.2
  multi_select_flutter: ^4.1.3
  go_router: ^16.1.0
  image_picker: ^1.0.4
  multi_image_picker_view: ^3.0.0
  carousel_slider: ^5.1.1
  get_time_ago: ^2.3.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Source
      fonts:
        - asset: fonts/SourceSerif4-Medium.ttf
    
    - family: Sora
      fonts:
        - asset: fonts/sora.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
